name: Playwright Tests

on:
  push:
    branches: [gh-actions, master]
  pull_request:
    branches: [gh-actions, master]

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (npm ci or npm install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "package-lock.json not found, running npm install instead"
            npm install
          fi

      - name: Run your tests
        run: npx playwright test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_dir: allure-history
          keep_files: true
