name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npm install --save-dev playwright@1.48
      - name: Run Playwright tests
        run: npx playwright test
